##################################
#           resolvable           #
##################################
version: '2'
services:
  resolvable:
    image: mgood/resolvable
    container_name: resolvable
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/resolv.conf:/tmp/resolv.conf

  zookeeper1:
    image: zookeeper
    hostname: zookeeper1
    expose:
      - 2181
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: zookeeper
    hostname: zookeeper2
    expose:
      - 2181
    environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    image: zookeeper
    hostname: zookeeper3
    expose:
      - 2181
    environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  drillbit1:
    image: gallna/apache-drill:drillbit
    container_name: drillbit1
    hostname: drillbit1
    expose:
      - 31010
      - 31011
      - 31012
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    volumes:
      - ./drillbit/drill-override.conf:/opt/drill/conf/drill-override.conf
      - ./drillbit/drillbit.sh:/opt/drill/drillbit.sh
    working_dir: /opt/drill
    environment:
      DRILL_HOME: /opt/drill
      DRILL_LOG_DIR: /opt/drill/logs
    entrypoint:
        - ./drillbit.sh
    command:
      - "tail"
      - "-f"
      - "/opt/drill/logs/drillbit.log"

  drillbit2:
    image: gallna/apache-drill:drillbit
    container_name: drillbit2
    hostname: drillbit2
    expose:
      - 31010
      - 31011
      - 31012
    links:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  drill:
    image: gallna/apache-drill:sqlline
    tty: true
    expose:
      - 8047

  zk-client:
    image: gallna/apache-drill:sqlline
    tty: true
    expose:
      - 8047
    links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    depends_on:
      - drillbit1
      - drillbit2
    command: ["-u", "jdbc:drill:schema=dfs;zk=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"]

  drillbit-client:
    image: gallna/apache-drill:sqlline
    tty: true
    expose:
      - 8047
    links:
      - drillbit1
      - drillbit2
    command: ["-u", "jdbc:drill:schema=dfs;drillbit=drillbit1:31010,drillbit2:31010"]
